### ISSUE TITLE
Table with temperature on a single point

### ISSUE THREAD

**Issue by annefou** [DataRockMyWorld/DataRockMyWorld.github.io#3]
> On the 24th of March, at 6pm GMT, the air temperature at 2 meters for the country was about 30 degrees celsius:

The value is on one single point (lat 5.5 and lon -0.5) so it does not correspond to the entire country.  Is it around Adenta Municipality? 

In the table we have 17:00:00 UTC. So we should have 5pm GMT not 6, right?

In your story, you mention the difficulties to sleep when it is too hot. You chose to display the temperature at 17:00 UTC: can you tell us a bit more why this time is important?

**Comment by DataRockMyWorld** [comment]
Yes the data is focused on Adenta municipality. Thanks for the observation.

I used 17:00 UTC because I thought the question asked us to use the last temperature of our last day.

I have corrected it since to the maximum temperature recorded in the day, 2pm GMT/ 14:00 UTC.
The idea is to show how high temperatures can go in my area.

I believe this is more consistent with the storyline.
